### ISSUE TITLE
English model question

### ISSUE THREAD

**Issue by cainesap** [bnosac/udpipe.models.ud#1]
Hello, thank you for this great resource!
A question about the training data for the English model you make available. Was it trained on the Universal Dependencies English Web Treebank (EWT)? That's the oldest and largest UD English treebank (I think) so I assume it's that corpus, but there are now 5 others so just wanted to check.. https://universaldependencies.org/en/index.html
best wishes, Andrew

**Comment by jwijffels** [comment]
Yes, it was trained on that treebank.
